version: "3.9"
services:
    maps:
        image: cadvanced/process_maps:latest
        restart: always
        volumes:
            - ./.env:/.env:ro
            - maps:/usr/local/apache2/htdocs/maps
            - map_upload:/usr/local/apache2/htdocs/map_upload
        env_file: .env
    db:
        image: cadvanced/cadvanced-db:latest
        restart: always
        volumes:
            - ./.env:/.env:ro
            - db:/var/lib/postgresql/data
        env_file: .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    api:
        image: cadvanced/cadvanced-api:latest
        restart: always
        volumes:
            - ./.env:/.env:ro
            - map_upload:/usr/local/apache2/htdocs/map_upload
            - logo_upload:/usr/local/apache2/htdocs/logo_upload
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
    frontend:
        image: cadvanced/cadvanced-frontend:latest
        env_file: .env
        restart: always
        volumes:
            - ./.env:/.env:ro
            - maps:/usr/local/apache2/htdocs/maps
            - logo_upload:/usr/local/apache2/htdocs/logo_upload
        ports:
            - "80:80"
volumes:
    db:
        driver: local
    maps:
        driver: local
    map_upload:
        driver: local
    logo_upload:
        driver: local
